### ISSUE TITLE
Support for text/Template missingkey=error Option 

### ISSUE THREAD

**Issue by chekolyn** [sanggonlee/gosq#2]
The default behavior for text Template is to add ```<no value>``` when a key is missing.

text/template has different options:
tmpl, err := template.New("").Option("missingkey=error).Parse(text) 

would error out if there is a key missing; this would be a nice option to error early instead of finding out the query is not valid after trying in the query in the DB.

**Comment by chekolyn** [comment]
There are a couple of ways to do this, but don't know how you prefer to handle it. 

We can modify the existing function and make that the default 
```golang 
func Execute(str string, args interface{}) (string, error) {
	tmpl, err := template.New("gosq").Option("missingkey=error").Parse(str)
	if err != nil {
		return "", errors.Wrap(err, "parsing template")
	}

	var buf bytes.Buffer
	if err = tmpl.Execute(&buf, args); err != nil {
		return "", errors.Wrap(err, "executing template")
	}

	return buf.String(), nil
}
```


 or we can create a new function something like this 

```golang
func ExecuteWithOption(str string, option string, args interface{}) (string, error) {
	if option == "" {
		option = "missingkey=default"
	}
	tmpl, err := template.New("gosq").Option(option).Parse(str)
	if err != nil {
		return "", errors.Wrap(err, "parsing template")
	}

	var buf bytes.Buffer
	if err = tmpl.Execute(&buf, args); err != nil {
		return "", errors.Wrap(err, "executing template")
	}

	return buf.String(), nil
}
```

**Comment by sanggonlee** [comment]
@chekolyn Thanks for reporting this. The first method is a breaking change so I think for now the second method should be good. Let me have a look sometime this week. If you prefer, please feel free to open a PR!

**Comment by chekolyn** [comment]
Sounds good I'll do a PR
